---
apiVersion: v1
kind: Service
metadata:
  name: dcn558-test-flask-service
  labels:
    username: dcn558
    env: test
spec:
  type: ClusterIP
  selector:
    app: dcn558-test-flask
  ports:
  - name: dcn558-test-flask
    port: 5000
    targetPort: 5000
