---
apiVersion: v1
kind: Service
metadata:
  name: dcn558-test-redis-service
  labels:
    username: dcn558
    env: test
spec:
  type: ClusterIP
  selector:
    app: dcn558-test-redis
  ports:
  - name: dcn558-test-redis
    port: 6379
    targetPort: 6379
