---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcn558-test-flask-deployment
  labels:
    username: dcn558
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dcn558-test-flask
  template:
    metadata:
      labels:
        app: dcn558-test-flask
    spec:
      containers:
        - name: flaskdeploys
          image: dcn558/gene_api
          env:
          - name: FLASK_APP
            value: 'gene_api.py'
          ports:
          - name: http
            containerPort: 5000
